We have movies dataset. We want to do some basic analysis such as,

1. What is the min, max and average rating for all movies?
1. What is the min, max and average rating for all bollywood movies?
1. What is the min, max and average rating for all hollywood movies?

We will see how this can be done first without using Pandas and then using Pandas

### Option 1 - Movies analysis without using Pandas

In [27]:
import csv

def calculate_rating_stats(data, industry=None):
    ratings = []
    for row in data:
        if row[3]!='NULL' and (not industry or row[1]==industry):
            ratings.append(float(row[3]))
    max_rating = max(ratings)
    min_rating = min(ratings)
    avg_rating = sum(ratings) / len(ratings)
    return max_rating, min_rating, avg_rating

with open('movies.csv') as f:
    data = list(csv.reader(f))
    header = data[0]
    data = data[1:]
    
    max_rating, min_rating, avg_rating = calculate_rating_stats(data)
    print(f"All records: Min rating = {min_rating}, Max rating = {max_rating}, Avg rating = {avg_rating}")
    
    max_rating, min_rating, avg_rating = calculate_rating_stats(data, industry="Bollywood")
    print(f"Bollywood: Min rating = {min_rating}, Max rating = {max_rating}, Avg rating = {avg_rating}")
    
    max_rating, min_rating, avg_rating = calculate_rating_stats(data, industry="Hollywood")
    print(f"Hollywood: Min rating = {min_rating}, Max rating = {max_rating}, Avg rating = {avg_rating}")

All records: Min rating = 1.9, Max rating = 9.3, Avg rating = 7.919444444444445
Bollywood: Min rating = 1.9, Max rating = 8.4, Avg rating = 7.656250000000001
Hollywood: Min rating = 6.8, Max rating = 9.3, Avg rating = 8.130000000000003

### Option 2 - Movies analysis using Pandas

**Print highest, lowest and average movie rating**

In [5]:
import pandas as pd

df = pd.read_csv("movies.csv")
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu

In [6]:
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [11]:
print(f'Max rating is {df.imdb_rating.max()}')

Max rating is 9.3

In [12]:
print(f'Min rating is {df.imdb_rating.min()}')

Min rating is 1.9

In [13]:
print(f'Average rating is {df.imdb_rating.mean()}')

Average rating is 7.919444444444445

**Print highest, lowest and average movie rating in bollywood and hollywood individually**|

In [23]:
df_hollywood = df.imdb_rating[df.industry == 'Hollywood']
df_bollywood = df.imdb_rating[df.industry == 'Bollywood']

print(f'Highest rating of Hollywood movies is {df_hollywood.max()}')
print(f'Highest rating of Bollywood movies is {df_bollywood.max()}')

Highest rating of Hollywood movies is 9.3
Highest rating of Bollywood movies is 8.4

In [25]:
print(f'Lowest rating of Hollywood movies is {df_hollywood.min()}')
print(f'Lowest rating of Bollywood movies is {df_bollywood.min()}')

Lowest rating of Hollywood movies is 6.8
Lowest rating of Bollywood movies is 1.9

In [26]:
print(f'Average rating of Hollywood movies is {df_hollywood.mean()}')
print(f'Average rating of Bollywood movies is {df_bollywood.mean()}')

Average rating of Hollywood movies is 8.130000000000003
Average rating of Bollywood movies is 7.656250000000001

Complete code of pandas analysis

In [27]:
df = pd.read_csv("movies.csv")
print("All movies: Min=", df.imdb_rating.min(), "Max=", df.imdb_rating.max(), "Avg=", df.imdb_rating.mean())

df_b = df[df.industry=="Bollywood"]
df_h = df[df.industry=="Hollywood"]

print("Bollywood: Min=", df_b.imdb_rating.min(), "Max=", df_b.imdb_rating.max(), "Avg=", df_b.imdb_rating.mean())
print("Hollywood: Min=", df_h.imdb_rating.min(), "Max=", df_h.imdb_rating.max(), "Avg=", df_h.imdb_rating.mean())

All movies: Min= 1.9 Max= 9.3 Avg= 7.919444444444445
Bollywood: Min= 1.9 Max= 8.4 Avg= 7.656250000000001
Hollywood: Min= 6.8 Max= 9.3 Avg= 8.130000000000003